const data = [
  {
    id: 'medium-valid-list-system-design-interview-phases-1',
    difficulty: 'medium',
    prompt: 'Select all items that are valid phases of a strong system design interview flow.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'A robust flow is: clarify requirements and constraints, estimate scale, propose high-level architecture, drill into data/API/storage decisions, and discuss tradeoffs plus bottlenecks.',
    validList: {
      helperText: 'Pick every phase that belongs in the interview flow.',
      items: [
        'Clarify functional and non-functional requirements',
        'Estimate scale (traffic, storage, throughput)',
        'Propose high-level architecture/components',
        'Deep-dive on data model, APIs, and storage strategy',
        'Discuss bottlenecks, tradeoffs, and failure handling',
        'Jump straight to implementation details before requirements',
        'Skip capacity discussion to save time',
        'Avoid tradeoff discussion to keep design simple',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-requirements-clarification-2',
    difficulty: 'medium',
    prompt: 'During requirement clarification for a new system, select all questions that are valid and useful to ask early.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Early requirement questions should cover scale, latency/availability targets, consistency expectations, and key product behaviors. These shape architecture decisions immediately.',
    validList: {
      helperText: 'Choose all requirement-clarification prompts you should ask up front.',
      items: [
        'What are target read/write QPS and expected peak multipliers?',
        'What latency SLOs are required for critical user actions?',
        'What availability target is required (e.g., 99.9, 99.99)?',
        'What consistency level is needed for core operations?',
        'What are the top user-facing workflows to optimize first?',
        'Can we defer all non-functional requirements until after coding?',
        'Should architecture avoid discussing failure modes?',
        'Can we skip constraints because scaling can be added later?',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-capacity-estimation-inputs-3',
    difficulty: 'medium',
    prompt: 'You are doing first-pass capacity planning for a system design. Select all inputs that are valid and necessary for rough sizing.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Good first-pass sizing depends on traffic volume, payload sizes, retention, concurrency/peak patterns, and growth assumptions. These drive compute, storage, and network needs.',
    validList: {
      helperText: 'Select all sizing inputs that belong in first-pass capacity estimation.',
      items: [
        'Average and peak request rates',
        'Request/response payload sizes',
        'Data retention period requirements',
        'Concurrency profile and traffic burst patterns',
        'Expected growth rate over time',
        'Preferred UI theme color choices',
        'Interview room whiteboard marker color',
        'Favorite programming language of the interviewer',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-leaderboard-design-checklist-4',
    difficulty: 'medium',
    prompt: 'For designing a global leaderboard service, select all valid core design concerns.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'A robust leaderboard design addresses ranking data structures, update/read patterns, anti-cheat protections, regional distribution, and correctness under concurrency.',
    validList: {
      helperText: 'Pick all items that should be part of the leaderboard design checklist.',
      items: [
        'Ordered index / sorted-set strategy for rank queries',
        'High-frequency score update path and write amplification',
        'Top-N and around-me query patterns',
        'Abuse prevention and score validation strategy',
        'Multi-region replication and staleness tolerance',
        'Avoiding any data model discussion',
        'Client-only leaderboard with no server truth',
        'No plan for duplicate/replayed score submissions',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-rate-limiting-strategies-5',
    difficulty: 'medium',
    prompt: 'You are protecting a public API from abuse. Select all valid controls you should consider in the design.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'A practical abuse-control design combines identity-aware limits, burst handling, adaptive controls, and observability for enforcement outcomes.',
    validList: {
      helperText: 'Choose all controls that are valid in a real API rate-limiting strategy.',
      items: [
        'Per-user or per-key quotas',
        'Token-bucket or leaky-bucket for burst smoothing',
        'Separate limits for read and write endpoints',
        'Progressive penalties for repeat abuse',
        'Monitoring and alerting on throttling/error ratios',
        'No authentication context for limit decisions',
        'Disable all limits during peak hours',
        'Only rely on client-side throttling',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-feed-system-components-6',
    difficulty: 'medium',
    prompt: 'For a social feed system, select all components that are valid and commonly required in production designs.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Production feed designs need ingestion, fanout strategies, ranking, storage/indexing, and anti-abuse controls.',
    validList: {
      helperText: 'Pick all components you would normally include in a scalable feed architecture.',
      items: [
        'Write path for posts/events ingestion',
        'Fanout strategy (push, pull, or hybrid)',
        'Ranking service or ranking rules engine',
        'Timeline storage and retrieval index',
        'Spam/abuse filtering hooks',
        'Single global lock around every feed read',
        'No backpressure or queueing during spikes',
        'Only in-memory feed with no persistence',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-idempotency-payment-api-7',
    difficulty: 'medium',
    prompt: 'When designing a payments API, select all valid mechanisms that help enforce idempotency for retry safety.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Idempotency requires stable keys, dedupe storage, bounded retention windows, and deterministic replay behavior for duplicate requests.',
    validList: {
      helperText: 'Select all valid idempotency mechanisms.',
      items: [
        'Client-provided idempotency key',
        'Server-side dedupe table keyed by idempotency key',
        'Persist prior response metadata for duplicate requests',
        'Define expiration/TTL policy for key retention',
        'Reject conflicting payload reuse for same key',
        'Generate a new key on every retry automatically',
        'Process duplicate requests in parallel without dedupe',
        'Ignore request body mismatch for same key',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-observability-core-8',
    difficulty: 'medium',
    prompt: 'For a distributed service rollout, select all observability signals that are valid core pillars to instrument from day one.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Core observability combines metrics, logs, and traces, with SLO-oriented alerting and dependency visibility.',
    validList: {
      helperText: 'Pick all signals that belong in baseline observability.',
      items: [
        'Request latency and error-rate metrics',
        'Structured logs with request/context identifiers',
        'Distributed tracing across service boundaries',
        'SLO-based alert thresholds',
        'Dependency health dashboards',
        'Manual screenshots instead of metrics',
        'No correlation IDs in logs',
        'Only monitor CPU and ignore request success/failure',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-blob-storage-vs-db-9',
    difficulty: 'medium',
    prompt: 'Select all valid reasons to store large user-uploaded media in object/blob storage rather than directly in a relational row.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Object storage is usually better for large binary payloads due to cost profile, serving patterns, and scaling model, while metadata remains in the relational layer.',
    validList: {
      helperText: 'Pick all valid design reasons for object storage in media pipelines.',
      items: [
        'Better cost/scalability profile for large binary blobs',
        'Efficient CDN integration and signed URL access patterns',
        'Keep relational database focused on metadata and queries',
        'Supports lifecycle/retention tiers for old objects',
        'Separates hot transactional data from heavy media payloads',
        'Relational storage is always cheaper for massive files',
        'Binary blobs in rows always improve query latency',
        'No metadata store is needed for uploaded assets',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-backpressure-strategies-10',
    difficulty: 'medium',
    prompt: 'A downstream dependency is slowing and your queue is growing quickly. Select all valid backpressure techniques.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Backpressure is about controlled shedding, bounded queues, adaptive producers, and safe degradation to prevent cascading failure.',
    validList: {
      helperText: 'Choose all actions that are valid backpressure controls.',
      items: [
        'Bound queue sizes and reject beyond limits',
        'Rate-limit producers based on downstream health',
        'Prioritize critical traffic classes',
        'Add circuit breakers/timeouts for failing dependencies',
        'Serve fallback responses for non-critical requests',
        'Allow unbounded queue growth indefinitely',
        'Retry every failure immediately with no jitter',
        'Disable all admission control during incidents',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-search-system-components-11',
    difficulty: 'medium',
    prompt: 'You are designing a search feature for documents. Select all components that are valid in a scalable search architecture.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'Production search systems combine ingestion/indexing pipelines with query-time ranking and operational controls like freshness handling.',
    validList: {
      helperText: 'Pick all components that normally belong in search design.',
      items: [
        'Ingestion pipeline from source of truth to index',
        'Indexer with tokenization/normalization rules',
        'Query service with ranking and relevance scoring',
        'Freshness/update strategy for index lag',
        'Result cache for repeated popular queries',
        'No indexing, only full scan at query time',
        'Single global mutex for all searches',
        'Ignore typo tolerance and language normalization entirely',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
  {
    id: 'medium-valid-list-api-gateway-roles-12',
    difficulty: 'medium',
    prompt: 'Select all responsibilities that are valid for an API gateway in front of multiple backend services.',
    options: ['Correct subset selected', 'Incorrect subset selected'],
    correctIndex: 0,
    correctExplanation:
      'API gateways are commonly used for auth/rate controls, routing, policy enforcement, and cross-cutting observability concerns.',
    validList: {
      helperText: 'Choose all common, valid API gateway responsibilities.',
      items: [
        'Authentication/authorization checks',
        'Rate limiting and quota enforcement',
        'Request routing and version-based traffic steering',
        'Centralized logging/metrics/tracing hooks',
        'Protocol translation for client compatibility',
        'Owning all domain business logic permanently',
        'Storing all primary relational data',
        'Removing need for service-level health checks',
      ],
      validIndices: [0, 1, 2, 3, 4],
    },
  },
]

export default data
