import { buildLeetcodePatternQuestion } from '../patternOptions'

function richPrompt(params: {
  title: string
  fullProblem: string
  io: string
  constraints: string
  objective: string
}): string {
  return (
    `${params.title}\n\n` +
    `Full Problem Statement: ${params.fullProblem}\n` +
    `Input/Output Requirements: ${params.io}\n` +
    `Constraints and Edge Cases: ${params.constraints}\n\n` +
    `Pattern Selection Question: ${params.objective}`
  )
}

const data = [
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc924-minimize-malware-spread-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 924 - Minimize Malware Spread', fullProblem: 'Given graph adjacency matrix and initially infected nodes, remove one infected node to minimize final malware spread; break ties by smallest index.', io: 'Input: graph matrix, initial infected list. Output: node index to remove.', constraints: 'Need component-level analysis of infection sources and exclusive infection impact.', objective: 'Which connectivity pattern unions components and compares infection ownership impact?' }), correctPattern: 'Disjoint Set Union (DSU / Union-Find)', correctExplanation: 'Union graph components, count infected per component, and select node that uniquely infects largest component.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc928-minimize-malware-spread-ii-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 928 - Minimize Malware Spread II', fullProblem: 'In graph with initially infected nodes, remove one initial node to minimize eventual infected count where infection spreads through edges.', io: 'Input: graph matrix and initial list. Output: index of node to remove.', constraints: 'Need evaluate how removed source affects clean components reachable from infected set.', objective: 'Which graph traversal pattern computes source reachability influence over clean components?' }), correctPattern: 'Graph DFS (Connected Components / Path Finding)', correctExplanation: 'Traverse clean components and track which infected sources can reach each to compute exclusive saves.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc936-stamping-the-sequence-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 936 - Stamping The Sequence', fullProblem: 'Given stamp and target strings, return sequence of stamp positions to form target from question marks in at most 10*target length moves, or empty if impossible.', io: 'Input: stamp and target. Output: list of stamping indices.', constraints: 'Need reverse-process style reductions with progress tracking and pruning.', objective: 'Which constraint-propagation pattern iteratively reduces unresolved positions until completion?' }), correctPattern: 'Pruning and Constraint Propagation', correctExplanation: 'Repeatedly apply stampable windows that reveal new progress, tracking visited windows to avoid loops.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc943-find-the-shortest-superstring-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 943 - Find the Shortest Superstring', fullProblem: 'Given array of strings, return shortest string containing each string as substring at least once.', io: 'Input: words array. Output: one shortest superstring.', constraints: 'Need maximize overlaps while visiting each word exactly once in sequence.', objective: 'Which compressed-state DP pattern over subsets and ending node handles this?' }), correctPattern: 'Bitmask DP', correctExplanation: 'DP[mask][last] stores best superstring (or overlap score) for subset mask ending at last word.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc952-largest-component-size-by-common-factor-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 952 - Largest Component Size by Common Factor', fullProblem: 'Given integers, connect numbers sharing factor > 1 and return size of largest connected component.', io: 'Input: nums array. Output: largest component size.', constraints: 'Need factorization-based connectivity without O(n^2) pair checks.', objective: 'Which pattern unions numbers through shared prime factors efficiently?' }), correctPattern: 'Disjoint Set Union (DSU / Union-Find)', correctExplanation: 'Factor each number and union number index/group roots by common factors, then count root sizes.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc956-tallest-billboard-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 956 - Tallest Billboard', fullProblem: 'Given rods, split into two groups with equal height maximizing that height.', io: 'Input: rods array. Output: maximum equal support height.', constraints: 'State depends on height difference and best achievable shorter-side height.', objective: 'Which DP pattern over compressed difference states is suitable?' }), correctPattern: 'Bitmask DP', correctExplanation: 'Use map/dp of difference -> max lower height, updating by placing rod on either side or skipping.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc960-delete-columns-to-make-sorted-iii-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 960 - Delete Columns to Make Sorted III', fullProblem: 'Given equal-length strings, delete minimum number of columns so remaining columns keep rows non-decreasing lexicographically.', io: 'Input: array of strings. Output: minimum deletions.', constraints: 'Need column subsequence optimization under pairwise row ordering constraints.', objective: 'Which subsequence DP pattern over columns applies?' }), correctPattern: 'Longest Increasing Subsequence (LIS) Pattern', correctExplanation: 'Treat columns as positions and compute longest valid non-decreasing column chain across all rows.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc964-least-operators-to-express-number-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 964 - Least Operators to Express Number', fullProblem: 'Using only number x and operators plus, minus, multiply, divide, express target with minimum operators.', io: 'Input: x and target. Output: minimum operator count.', constraints: 'Need recursive decomposition by powers of x with carry/borrow tradeoffs.', objective: 'Which dynamic programming style over numeric decomposition states is best?' }), correctPattern: '1D DP (Fibonacci / Climbing Stairs Pattern)', correctExplanation: 'Memoized recursion/DP on target decomposed by base-x digits minimizes operator cost with carry choices.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc968-binary-tree-cameras-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 968 - Binary Tree Cameras', fullProblem: 'Place minimum cameras on tree nodes where each camera covers parent, self, and children.', io: 'Input: root node. Output: minimum number of cameras.', constraints: 'Need postorder state classification of node coverage status.', objective: 'Which tree dynamic programming pattern computes optimal coverage states bottom-up?' }), correctPattern: 'DP on Trees', correctExplanation: 'Postorder states (has camera, covered, not covered) drive greedy-optimal camera placement count.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc975-odd-even-jump-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 975 - Odd Even Jump', fullProblem: 'From index i, odd jumps go to smallest value >= nums[i] to the right, even jumps go to largest value <= nums[i] to right; count good starting indices reaching end.', io: 'Input: nums array. Output: number of good start indices.', constraints: 'Need precompute jump destinations and DP reachability by parity.', objective: 'Which boundary-search pattern is used to find next greater-or-equal / less-or-equal targets?' }), correctPattern: 'Binary Search for Boundary / First-Last Occurrence', correctExplanation: 'Ordered maps/boundary lookups find next jump indices, then DP backward for odd/even reachability.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc982-triples-with-bitwise-and-equal-to-zero-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 982 - Triples with Bitwise AND Equal To Zero', fullProblem: 'Count triples (i,j,k) where nums[i] & nums[j] & nums[k] == 0.', io: 'Input: nums array. Output: number of valid triples.', constraints: 'Need optimize beyond O(n^3) using bitmask frequency convolution ideas.', objective: 'Which pattern based on bitmask state counting applies?' }), correctPattern: 'Bitmask DP', correctExplanation: 'Precompute pairwise AND frequencies by mask and aggregate compatible third elements.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc987-vertical-order-traversal-of-a-binary-tree-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 987 - Vertical Order Traversal of a Binary Tree', fullProblem: 'Return vertical traversal where nodes grouped by column from left to right; within same row/column sort by value.', io: 'Input: tree root. Output: list of vertical columns.', constraints: 'Need row/col coordinate assignment and stable ordering.', objective: 'Which level traversal pattern naturally annotates coordinates breadth-wise for sorting/grouping?' }), correctPattern: 'Tree BFS / Level Order', correctExplanation: 'BFS/DFS assign row/col; collect tuples then sort by column,row,value and group columns.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc995-minimum-number-of-k-consecutive-bit-flips-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 995 - Minimum Number of K Consecutive Bit Flips', fullProblem: 'Given binary array and k, flip any length-k subarray (invert bits). Return minimum flips to make all bits 1 or -1.', io: 'Input: nums binary array and k. Output: minimum flips or -1.', constraints: 'Need linear-time lazy flip effect tracking over sliding window.', objective: 'Which fixed-size sliding pattern tracks active flip parity efficiently?' }), correctPattern: 'Sliding Window (Fixed Size)', correctExplanation: 'Use queue/difference parity to track whether current bit is effectively flipped odd/even times.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc996-number-of-squareful-arrays-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 996 - Number of Squareful Arrays', fullProblem: 'Count permutations where sum of every adjacent pair is a perfect square.', io: 'Input: nums array (with duplicates possible). Output: number of squareful permutations.', constraints: 'Need permutation enumeration with duplicate handling and adjacency feasibility pruning.', objective: 'Which search pattern uses pruning and permutation construction constraints?' }), correctPattern: 'Pruning and Constraint Propagation', correctExplanation: 'Backtrack on multiset counts, only extend with values forming square sums with previous value.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1000-minimum-cost-to-merge-stones-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1000 - Minimum Cost to Merge Stones', fullProblem: 'Merge exactly k consecutive piles repeatedly into one pile with cost equal to merged total stones. Return minimum cost or -1 if impossible.', io: 'Input: stones array and k. Output: minimum total cost or -1.', constraints: 'Need interval transitions with merge-count feasibility constraints.', objective: 'Which interval DP family over ranges and partition points applies?' }), correctPattern: 'Palindromic Substring / Subsequence DP', correctExplanation: 'Interval DP computes minimum cost to reduce ranges to specific pile counts and merges with prefix sums for costs.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1028-recover-a-tree-from-preorder-traversal-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1028 - Recover a Tree From Preorder Traversal', fullProblem: 'Given preorder string where node depth encoded by dashes, reconstruct binary tree.', io: 'Input: encoded preorder string. Output: tree root.', constraints: 'Need parse depth and attach nodes respecting preorder parent-child relation.', objective: 'Which root-first tree construction pattern is most natural?' }), correctPattern: 'Tree DFS (Pre-order)', correctExplanation: 'Preorder parsing with depth tracking reconstructs nodes in root-left-right sequence recursively/iteratively.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1032-stream-of-characters-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1032 - Stream of Characters', fullProblem: 'Design data structure receiving query letters and returning whether any suffix of stream matches a dictionary word.', io: 'Input: word list and character stream queries. Output: boolean per query.', constraints: 'Need efficient suffix matching over growing stream.', objective: 'Which pattern uses prefix-tree over reversed words for suffix checks?' }), correctPattern: 'Trie (Prefix Tree)', correctExplanation: 'Insert reversed words into trie and walk backward through recent stream characters at each query.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1044-longest-duplicate-substring-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1044 - Longest Duplicate Substring', fullProblem: 'Find one longest substring appearing at least twice in string s.', io: 'Input: string s. Output: longest duplicate substring.', constraints: 'Need efficient length feasibility checks over huge candidate set.', objective: 'Which pattern searches substring length answer space with monotonic feasibility?' }), correctPattern: 'Binary Search on Answer Space', correctExplanation: 'Binary search candidate length and use rolling hash/set to detect duplicates of that length.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1074-number-of-submatrices-that-sum-to-target-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1074 - Number of Submatrices That Sum to Target', fullProblem: 'Count submatrices whose element sum equals target.', io: 'Input: matrix and target. Output: count of matching submatrices.', constraints: 'Need reduce 2D problem to repeated 1D subarray-sum count computations.', objective: 'Which cumulative-sum pattern is core to this counting approach?' }), correctPattern: 'Prefix Sum / Cumulative Sum', correctExplanation: 'Fix row boundaries, compress columns into 1D sums, then count target subarrays using prefix frequency map.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1095-find-in-mountain-array-additional-15', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1095 - Find in Mountain Array', fullProblem: 'Given mountain array API and target, find minimum index of target by querying values.', io: 'Input: target and mountain array interface. Output: index or -1.', constraints: 'Need locate peak then search increasing and decreasing segments efficiently.', objective: 'Which binary-search family over boundary and ordered halves applies?' }), correctPattern: 'Rotated Sorted Array Search', correctExplanation: 'Binary search peak, then binary search ascending left half and descending right half with direction-aware comparisons.' }),
]

export default data
