import { buildLeetcodePatternQuestion } from '../patternOptions'

function richPrompt(params: {
  title: string
  fullProblem: string
  io: string
  constraints: string
  objective: string
}): string {
  return (
    `${params.title}\n\n` +
    `Full Problem Statement: ${params.fullProblem}\n` +
    `Input/Output Requirements: ${params.io}\n` +
    `Constraints and Edge Cases: ${params.constraints}\n\n` +
    `Pattern Selection Question: ${params.objective}`
  )
}

const data = [
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc517-super-washing-machines-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 517 - Super Washing Machines', fullProblem: 'Given washing machines holding dresses, each move can pass one dress from selected machines to adjacent machines simultaneously. Return minimum moves to make all machines equal.', io: 'Input: machines array. Output: minimum moves or -1 if impossible.', constraints: 'Need global average feasibility and local transfer load analysis.', objective: 'Which cumulative load pattern captures net transfer imbalances across positions?' }), correctPattern: 'Prefix Sum / Cumulative Sum', correctExplanation: 'Running imbalance and local surplus determine required moves; answer is max of absolute imbalance and local excess.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc527-word-abbreviation-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 527 - Word Abbreviation', fullProblem: 'Given distinct words, produce minimal unique abbreviations for each word.', io: 'Input: words array. Output: abbreviations array preserving order.', constraints: 'Need detect collisions among abbreviated forms and refine conflicting groups.', objective: 'Which pattern uses indexed hashing/grouping by abbreviation signatures and iterative refinement?' }), correctPattern: 'In-place Array Hashing / Marking', correctExplanation: 'Group by tentative abbreviations using hash maps, then increase prefix lengths for conflicting groups.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc546-remove-boxes-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 546 - Remove Boxes', fullProblem: 'Remove contiguous equal-color box groups; removing k equal boxes scores k*k points. Maximize total score.', io: 'Input: boxes array. Output: maximum score.', constraints: 'State depends on interval and carry count of same-colored boxes merged from left.', objective: 'Which interval dynamic-programming family is appropriate for this optimization?' }), correctPattern: 'Palindromic Substring / Subsequence DP', correctExplanation: 'Use interval DP with extra parameter for carry-over equal boxes to model merge gains.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc552-student-attendance-record-ii-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 552 - Student Attendance Record II', fullProblem: 'Count valid attendance strings of length n with fewer than 2 absences and no 3 consecutive lates.', io: 'Input: integer n. Output: number of valid records modulo mod.', constraints: 'Need finite-state transitions over length with absence and late counters.', objective: 'Which DP pattern over small state grid best models these transitions?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP[length][absences][consecutiveLates] transitions by adding P, A, or L under constraints.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc564-find-the-closest-palindrome-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 564 - Find the Closest Palindrome', fullProblem: 'Given integer n as string, return nearest integer palindrome not equal to n, tie by smaller value.', io: 'Input: numeric string n. Output: closest palindrome string.', constraints: 'Need generate nearby palindrome candidates around prefix boundary cases.', objective: 'Which boundary-search style pattern compares nearby candidate palindromes around numeric boundaries?' }), correctPattern: 'Binary Search for Boundary / First-Last Occurrence', correctExplanation: 'Construct candidate palindromes from prefix-1, prefix, prefix+1 plus edge cases and choose nearest by ordered comparison.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc588-design-in-memory-file-system-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 588 - Design In-Memory File System', fullProblem: 'Design file system supporting ls, mkdir, addContentToFile, and readContentFromFile with hierarchical paths.', io: 'Input: sequence of path operations. Output: operation-specific results.', constraints: 'Need prefix-based path navigation and dynamic node creation.', objective: 'Which pattern naturally represents hierarchical path prefixes?' }), correctPattern: 'Trie (Prefix Tree)', correctExplanation: 'Use trie-like directory tree nodes keyed by path segments for efficient hierarchical operations.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc600-non-negative-integers-without-consecutive-ones-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 600 - Non-negative Integers without Consecutive Ones', fullProblem: 'Given n, count numbers in [0,n] whose binary representation contains no consecutive ones.', io: 'Input: integer n. Output: valid count.', constraints: 'Need digit-DP-like bit-state counting rather than checking each number.', objective: 'Which compressed-state bit-pattern DP is most suitable?' }), correctPattern: 'Bitmask DP', correctExplanation: 'Use bitwise DP/Fibonacci-like counts for valid prefixes and scan bits of n to accumulate answer.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc629-k-inverse-pairs-array-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 629 - K Inverse Pairs Array', fullProblem: 'Count arrays of numbers 1..n with exactly k inverse pairs.', io: 'Input: n and k. Output: count modulo mod.', constraints: 'Need optimized DP transition summations to avoid cubic complexity.', objective: 'Which DP pattern over a 2D state table with cumulative optimization applies?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP[n][k] with prefix-sum optimized transitions counts placements contributing inverse pairs.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc639-decode-ways-ii-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 639 - Decode Ways II', fullProblem: 'Decode message containing digits and wildcard star where star can represent digits 1-9. Return number of decodings modulo mod.', io: 'Input: string s. Output: decoding count.', constraints: 'Need per-position transitions for single-char and pair-char possibilities including wildcard cases.', objective: 'Which DP pattern over sequential positions handles combinational transition counts?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP over index with contributions from one-char and two-char decodings, expanded for wildcard combinations.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc642-design-search-autocomplete-system-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 642 - Design Search Autocomplete System', fullProblem: 'Design autocomplete system suggesting top historical sentences for current typed prefix with ranking by frequency then lexicographic order.', io: 'Input: stream of characters and sentence commits. Output: top suggestions for current prefix.', constraints: 'Need fast prefix retrieval and ranked candidate maintenance.', objective: 'Which prefix data structure pattern best supports incremental typed-prefix lookup?' }), correctPattern: 'Trie (Prefix Tree)', correctExplanation: 'Trie nodes keyed by character support prefix traversal; each node tracks candidate sentence rankings.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc664-strange-printer-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 664 - Strange Printer', fullProblem: 'A printer can print a sequence of identical chars in one turn over any interval, overwriting existing chars. Return minimum turns to print string s.', io: 'Input: string s. Output: minimum print turns.', constraints: 'Need interval decomposition where matching chars can reduce turns across splits.', objective: 'Which interval DP family over substrings fits this minimization?' }), correctPattern: 'Palindromic Substring / Subsequence DP', correctExplanation: 'Interval DP on substring bounds minimizes turns by merging operations when matching chars align.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc668-kth-smallest-number-in-multiplication-table-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 668 - Kth Smallest Number in Multiplication Table', fullProblem: 'Given m x n multiplication table, return k-th smallest number.', io: 'Input: m, n, k. Output: k-th smallest value.', constraints: 'Need monotonic count of values <= x to guide search.', objective: 'Which pattern binary-searches answer values using monotonic counting predicate?' }), correctPattern: 'Binary Search on Answer Space', correctExplanation: 'Binary search value x; count entries <= x by summing min(n, x/i) across rows.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc675-cut-off-trees-for-golf-event-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 675 - Cut Off Trees for Golf Event', fullProblem: 'In grid forest, cut trees in increasing height order. Return minimum total steps to reach and cut all trees, or -1 if impossible.', io: 'Input: forest grid. Output: minimum steps or -1.', constraints: 'Need repeated shortest path between successive targets on unweighted grid.', objective: 'Which shortest-path pattern in unweighted graphs should be reused repeatedly?' }), correctPattern: 'Graph BFS (Shortest Path in Unweighted Graph)', correctExplanation: 'Run BFS for each consecutive target pair in sorted tree order and accumulate path lengths.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc679-24-game-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 679 - 24 Game', fullProblem: 'Given four numbers, use operations plus, minus, multiply, divide and parentheses to determine if value 24 can be reached.', io: 'Input: four integers. Output: boolean whether 24 is achievable.', constraints: 'Need exhaustive operation ordering with floating precision tolerance and branch pruning.', objective: 'Which pattern performs recursive search with pruning over operation combinations?' }), correctPattern: 'Pruning and Constraint Propagation', correctExplanation: 'Backtrack over pair selections and operations, pruning symmetric/duplicate branches and checking epsilon near 24.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc683-k-empty-slots-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 683 - K Empty Slots', fullProblem: 'Given bloom day order of bulbs, find earliest day where two blooming bulbs have exactly k non-blooming bulbs between them.', io: 'Input: bulbs order and k. Output: earliest day or -1.', constraints: 'Need efficient validation of window minima over transformed bloom-day positions.', objective: 'Which fixed-size window pattern is commonly used for this earliest-valid-window check?' }), correctPattern: 'Sliding Window (Fixed Size)', correctExplanation: 'Transform to day array and scan windows of size k+2, validating interior days exceed boundary max day.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc689-maximum-sum-of-3-non-overlapping-subarrays-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 689 - Maximum Sum of 3 Non-Overlapping Subarrays', fullProblem: 'Find starting indices of three non-overlapping subarrays length k with maximum total sum.', io: 'Input: nums and k. Output: three starting indices maximizing total.', constraints: 'Need precomputed window sums and optimal left/right choices around middle window.', objective: 'Which pattern around fixed-length rolling windows best structures this optimization?' }), correctPattern: 'Sliding Window (Fixed Size)', correctExplanation: 'Compute all k-window sums and track best left/right windows for each middle index.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc699-falling-squares-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 699 - Falling Squares', fullProblem: 'Squares fall on number line intervals stacking on overlapping prior heights; return running maximum height after each drop.', io: 'Input: list of [left,size]. Output: array of max heights after each insertion.', constraints: 'Need interval overlap queries/updates and skyline-like accumulation.', objective: 'Which interval boundary-event pattern best represents these stacking updates?' }), correctPattern: 'Sweep Line Algorithm / Interval Boundary Events', correctExplanation: 'Track interval heights and overlap interactions as events/segments, updating running global maximum.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc710-random-pick-with-blacklist-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 710 - Random Pick with Blacklist', fullProblem: 'Pick uniformly random integer from [0,n) excluding blacklisted values, with many picks and preprocessing allowed.', io: 'Input: n and blacklist. Output: random valid picks uniformly distributed.', constraints: 'Need O(1) pick with remapping strategy from blocked low range into allowed high range.', objective: 'Which hashing/remapping pattern supports constant-time random pick after preprocessing?' }), correctPattern: 'In-place Array Hashing / Marking', correctExplanation: 'Map blacklisted numbers in sampling range to valid whitelisted numbers via hash map remapping.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc715-range-module-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 715 - Range Module', fullProblem: 'Design module supporting addRange, queryRange, and removeRange on real-number half-open intervals.', io: 'Input: interval update/query operations. Output: boolean responses for queries.', constraints: 'Need dynamic interval union/difference management.', objective: 'Which interval boundary-event pattern is central for maintaining covered ranges?' }), correctPattern: 'Sweep Line Algorithm / Interval Boundary Events', correctExplanation: 'Maintain ordered disjoint intervals and merge/split them on add/remove operations.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc719-find-k-th-smallest-pair-distance-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 719 - Find K-th Smallest Pair Distance', fullProblem: 'Given integer array, return k-th smallest absolute difference among all pairs.', io: 'Input: nums and k. Output: k-th smallest pair distance.', constraints: 'Distance threshold feasibility is monotonic after sorting.', objective: 'Which pattern binary-searches answer distance and counts pairs within threshold?' }), correctPattern: 'Binary Search on Answer Space', correctExplanation: 'Sort nums, binary search distance d, and count pairs with difference <= d using two pointers.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc732-my-calendar-iii-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 732 - My Calendar III', fullProblem: 'Support booking intervals and after each booking return maximum number of concurrent events seen so far.', io: 'Input: online booking intervals. Output: max overlap after each insertion.', constraints: 'Need accumulation of start/end boundary deltas over time.', objective: 'Which boundary-event accumulation pattern computes overlap peaks?' }), correctPattern: 'Sweep Line Algorithm / Interval Boundary Events', correctExplanation: 'Apply +1 at start and -1 at end, then evaluate running prefix over ordered boundaries for max overlap.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc736-parse-lisp-expression-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 736 - Parse Lisp Expression', fullProblem: 'Evaluate Lisp-like expression language containing let, add, mult with nested scopes and variable bindings.', io: 'Input: expression string. Output: evaluated integer.', constraints: 'Need nested expression parsing and scope stack handling.', objective: 'Which stack-oriented parsing pattern manages nested contexts effectively?' }), correctPattern: 'Monotonic Stack', correctExplanation: 'Recursive descent or explicit stacks track expression frames and scope maps across nested parentheses.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc741-cherry-pickup-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 741 - Cherry Pickup', fullProblem: 'Collect max cherries on grid by going from top-left to bottom-right and back, with blocked cells. Equivalent to two walkers moving forward simultaneously.', io: 'Input: grid with cherries and thorns. Output: maximum cherries collectable.', constraints: 'Need 3D state reduction with synchronized steps and overlap handling.', objective: 'Which grid/state dynamic programming pattern is used here?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP over step and two row indices (or row/col pairs) captures both walkers and avoids recomputation.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc749-contain-virus-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 749 - Contain Virus', fullProblem: 'Infected regions spread daily on grid; each day you can quarantine one region with walls. Compute total walls needed until spread stops.', io: 'Input: infection grid. Output: total walls built.', constraints: 'Need repeatedly identify most threatening component and simulate spread of others.', objective: 'Which component-traversal pattern identifies regions and their frontier cells each round?' }), correctPattern: 'Graph DFS (Connected Components / Path Finding)', correctExplanation: 'DFS/BFS labels regions, counts threatened cells/walls, quarantines max-threat region, and spreads others iteratively.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc757-set-intersection-size-at-least-two-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 757 - Set Intersection Size At Least Two', fullProblem: 'Given intervals, construct smallest set of integers such that every interval contains at least two chosen numbers.', io: 'Input: intervals array. Output: minimum set size.', constraints: 'Need greedy interval ordering and careful boundary placements.', objective: 'Which overlapping-interval pattern applies to greedy endpoint coverage?' }), correctPattern: 'Overlapping Intervals / Merge Intervals', correctExplanation: 'Sort intervals by end (with tie rules) and greedily place points near ends to satisfy coverage with minimal additions.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc761-special-binary-string-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 761 - Special Binary String', fullProblem: 'A special binary string has equal 1s and 0s and every prefix has at least as many 1s as 0s. Rearrange special substrings to make lexicographically largest string.', io: 'Input: special binary string. Output: lexicographically largest special string.', constraints: 'Need recursive decomposition into balanced primitive blocks and sorted recombination.', objective: 'Which pattern uses recursive decomposition plus pruning/ordering constraints?' }), correctPattern: 'Pruning and Constraint Propagation', correctExplanation: 'Split into primitive special blocks, recursively maximize inner content, then sort blocks descending before concatenation.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc765-couples-holding-hands-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 765 - Couples Holding Hands', fullProblem: 'People seated in row; couples are numbered (0,1), (2,3), etc. Compute minimum swaps so each couple sits together.', io: 'Input: seating array. Output: minimum swap count.', constraints: 'Need component/cycle understanding of partner misplacements.', objective: 'Which connectivity pattern can model and solve swaps via component structure?' }), correctPattern: 'Disjoint Set Union (DSU / Union-Find)', correctExplanation: 'Model couple-seat relationships as graph components; swaps equal sum(componentSize-1) over misplacement components.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc768-max-chunks-to-make-sorted-ii-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 768 - Max Chunks To Make Sorted II', fullProblem: 'Split array into max number of chunks so sorting each chunk individually and concatenating yields fully sorted array.', io: 'Input: integer array possibly with duplicates. Output: maximum chunks.', constraints: 'Need boundary detection where left max <= right min across split.', objective: 'Which monotonic structure pattern helps derive valid split boundaries?' }), correctPattern: 'Monotonic Stack', correctExplanation: 'Monotonic stack can merge invalid chunk boundaries and track chunk maxima robustly with duplicates.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc773-sliding-puzzle-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 773 - Sliding Puzzle', fullProblem: 'Given 2x3 board, return minimum moves to reach target configuration by swapping zero with neighbors.', io: 'Input: board state. Output: minimum moves or -1.', constraints: 'State space is unweighted and finite; shortest move sequence required.', objective: 'Which pattern guarantees shortest path in unweighted state graph?' }), correctPattern: 'Graph BFS (Shortest Path in Unweighted Graph)', correctExplanation: 'BFS over serialized board states finds minimum moves to target configuration.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc782-transform-to-chessboard-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 782 - Transform to Chessboard', fullProblem: 'Given binary matrix, return minimum row/column swaps to transform into chessboard pattern or -1 if impossible.', io: 'Input: n x n binary board. Output: minimum swaps or -1.', constraints: 'Need pattern-validity checks for row/column signatures and minimal swap counts.', objective: 'Which matrix pattern is used for structured row/column traversal and parity analysis?' }), correctPattern: 'Matrix Traversal (Spiral / Diagonal / Rotate)', correctExplanation: 'Traverse row/column patterns to validate chessboard constraints and compute minimal swap parity adjustments.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc786-kth-smallest-prime-fraction-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 786 - K-th Smallest Prime Fraction', fullProblem: 'Given sorted array of 1 and primes, return k-th smallest fraction arr[i]/arr[j] for i < j.', io: 'Input: prime array and k. Output: numerator/denominator pair.', constraints: 'Need ordered search over fraction values without enumerating all O(n^2) fractions.', objective: 'Which pattern binary-searches value space with counting fractions <= mid?' }), correctPattern: 'Binary Search on Answer Space', correctExplanation: 'Binary search fraction threshold and count valid fractions via two-pointer pass per denominator.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc793-preimage-size-of-factorial-zeroes-function-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 793 - Preimage Size of Factorial Zeroes Function', fullProblem: 'For given k, find how many non-negative integers x satisfy f(x)=k where f(x) counts trailing zeroes in x!.', io: 'Input: integer k. Output: size of preimage set.', constraints: 'Need monotonic trailing-zero count function and boundary search around k.', objective: 'Which pattern finds lower/upper boundaries for monotonic arithmetic function values?' }), correctPattern: 'Binary Search on Answer Space', correctExplanation: 'Binary-search smallest x with f(x)>=k and with f(x)>=k+1; difference gives preimage size.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc798-smallest-rotation-with-highest-score-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 798 - Smallest Rotation with Highest Score', fullProblem: 'Array rotated by k scores one point per element nums[i] <= its new index. Find smallest k with highest score.', io: 'Input: nums array. Output: best rotation k.', constraints: 'Need interval contribution of each element over rotation range.', objective: 'Which cumulative-delta pattern over rotation boundaries computes scores efficiently?' }), correctPattern: 'Prefix Sum / Cumulative Sum', correctExplanation: 'Use difference array over rotations to accumulate score deltas and pick max prefix-sum index.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc801-minimum-swaps-to-make-sequences-increasing-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 801 - Minimum Swaps To Make Sequences Increasing', fullProblem: 'Given two equal-length arrays, you may swap values at same index. Find minimum swaps so both arrays become strictly increasing.', io: 'Input: nums1 and nums2. Output: minimum swaps.', constraints: 'Transition depends on previous index states: swapped or not swapped.', objective: 'Which linear state-machine DP pattern models keep/swap transitions?' }), correctPattern: 'State Machine / Buy-Sell Stock DP', correctExplanation: 'Track two states per index: min swaps when keeping or swapping at current index, with compatibility checks.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc803-bricks-falling-when-hit-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 803 - Bricks Falling When Hit', fullProblem: 'Given grid of bricks and list of hits, return number of bricks that fall after each hit (excluding directly hit brick).', io: 'Input: grid and hits. Output: fall counts per hit.', constraints: 'Need efficient dynamic connectivity to top row under reverse processing.', objective: 'Which pattern supports connectivity restoration and component-size queries efficiently?' }), correctPattern: 'Disjoint Set Union (DSU / Union-Find)', correctExplanation: 'Process hits in reverse, union restored bricks, and measure newly connected component growth to stable roof node.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc805-split-array-with-same-average-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 805 - Split Array With Same Average', fullProblem: 'Determine if array can be split into two non-empty groups with equal average.', io: 'Input: nums array. Output: boolean feasibility.', constraints: 'Transforms to subset sum with cardinality constraints and large combinational search space.', objective: 'Which subset-DP pattern over counts and sums is commonly used?' }), correctPattern: '0/1 Knapsack Pattern', correctExplanation: 'Use knapsack-style DP/set states tracking possible sums for each subset size to test equal-average condition.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc810-chalkboard-xor-game-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 810 - Chalkboard XOR Game', fullProblem: 'Players erase one number per turn from array; if xor of remaining numbers becomes 0 before a move, current player loses. Determine if first player wins with optimal play.', io: 'Input: nums array. Output: boolean first-player winning status.', constraints: 'Game outcome has concise parity/xor invariant characterization.', objective: 'Which low-level bitwise invariant pattern is most relevant?' }), correctPattern: 'Bit Manipulation Tricks', correctExplanation: 'Winning condition reduces to xor-total and array parity properties under optimal play.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc815-bus-routes-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 815 - Bus Routes', fullProblem: 'Given bus routes, source stop, and target stop, find minimum number of buses to take to reach target.', io: 'Input: routes, source, target. Output: minimum buses or -1.', constraints: 'Need shortest transfers in unweighted graph of route transitions or stop-route states.', objective: 'Which pattern solves minimum-hop traversal in unweighted transit graph?' }), correctPattern: 'Graph BFS (Shortest Path in Unweighted Graph)', correctExplanation: 'BFS over routes/stops explores transfer layers; first time target reached gives minimum buses.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc827-making-a-large-island-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 827 - Making A Large Island', fullProblem: 'Given binary grid, flip at most one 0 to 1 and return largest possible island area.', io: 'Input: grid. Output: maximum island size after one optional flip.', constraints: 'Need precomputed component IDs/sizes and deduplicated neighbor component merging per zero cell.', objective: 'Which pattern tracks connected components and combines neighboring component sizes quickly?' }), correctPattern: 'Disjoint Set Union (DSU / Union-Find)', correctExplanation: 'Union existing land components, then for each zero sum unique adjacent component sizes plus one.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc829-consecutive-numbers-sum-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 829 - Consecutive Numbers Sum', fullProblem: 'Count ways to express n as sum of consecutive positive integers.', io: 'Input: integer n. Output: number of valid consecutive-sum representations.', constraints: 'Need arithmetic transformation over sequence length and divisibility conditions.', objective: 'Which cumulative arithmetic pattern is used to derive candidate sequence lengths efficiently?' }), correctPattern: 'Prefix Sum / Cumulative Sum', correctExplanation: 'Use n = k*x + k*(k-1)/2 relation to test lengths k that yield integer positive starts.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc850-rectangle-area-ii-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 850 - Rectangle Area II', fullProblem: 'Compute total area covered by axis-aligned rectangles, modulo 1e9+7, accounting for overlaps only once.', io: 'Input: rectangles list. Output: union area modulo mod.', constraints: 'Need overlap-safe area accumulation via event-based scan.', objective: 'Which interval boundary-event pattern handles rectangle union area computation?' }), correctPattern: 'Sweep Line Algorithm / Interval Boundary Events', correctExplanation: 'Sweep along x events and maintain active y-coverage length to accumulate area slices.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc878-nth-magical-number-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 878 - Nth Magical Number', fullProblem: 'A magical number is divisible by a or b. Return n-th magical number modulo 1e9+7.', io: 'Input: n, a, b. Output: n-th magical number mod mod.', constraints: 'Need lcm/gcd relation and monotonic count of divisible numbers <= x.', objective: 'Which mathematical gcd/lcm pattern is essential in this counting search?' }), correctPattern: 'Euclidean Algorithm', correctExplanation: 'Compute lcm via gcd and combine with binary search/counting of multiples by inclusion-exclusion.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc882-reachable-nodes-in-subdivided-graph-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 882 - Reachable Nodes In Subdivided Graph', fullProblem: 'Edges subdivide into new nodes; with max moves from node 0, count reachable original and subdivided nodes.', io: 'Input: weighted edges as subdivisions, maxMoves, n. Output: total reachable nodes.', constraints: 'Need shortest distances to original nodes plus partial edge reach accounting.', objective: 'Which weighted shortest-path pattern should compute best remaining moves per node?' }), correctPattern: "Dijkstra's Algorithm", correctExplanation: 'Run Dijkstra from node 0 to get minimal move cost to each node, then count reachable subdivided parts per edge.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc891-sum-of-subsequence-widths-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 891 - Sum of Subsequence Widths', fullProblem: 'For all non-empty subsequences, width is max-min. Return sum of widths modulo mod.', io: 'Input: nums array. Output: total width sum modulo mod.', constraints: 'Need combinational contribution counting of each element as max and min.', objective: 'Which cumulative counting pattern with sorted order and powers-of-two weights is used?' }), correctPattern: 'Prefix Sum / Cumulative Sum', correctExplanation: 'After sorting, each element contributes as max in 2^i subsets and as min in 2^(n-1-i) subsets.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc899-orderly-queue-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 899 - Orderly Queue', fullProblem: 'Given string s and integer k, you may choose one of first k letters and append it to end each move. Return lexicographically smallest possible string.', io: 'Input: s and k. Output: lexicographically smallest obtainable string.', constraints: 'For k=1 only rotations allowed; for k>1 full permutation sorting effect occurs.', objective: 'Which sequence-scanning pattern is used when evaluating best rotation candidate cases?' }), correctPattern: 'Two Pointers (Same Direction / Fast and Slow)', correctExplanation: 'For k=1 compare all rotations (often via linear scanning tricks); for k>1 result is sorted string.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc902-numbers-at-most-n-given-digit-set-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 902 - Numbers At Most N Given Digit Set', fullProblem: 'Given allowed digit set and integer n, count how many positive integers <= n can be formed using digits (repetition allowed).', io: 'Input: digits set and n. Output: count of valid numbers.', constraints: 'Need positional DP/counting across prefix bound of n.', objective: 'Which positional dynamic programming pattern over digit prefixes applies?' }), correctPattern: '1D DP (Fibonacci / Climbing Stairs Pattern)', correctExplanation: 'Count shorter lengths directly and use prefix-constrained DP for equal-length numbers up to n.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc903-valid-permutations-for-di-sequence-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 903 - Valid Permutations for DI Sequence', fullProblem: 'Given string s of D and I, count permutations of [0..n] that satisfy descent/increase pattern.', io: 'Input: DI string. Output: count modulo mod.', constraints: 'Need DP with prefix-sum optimization for transitions across rank positions.', objective: 'Which table-based DP pattern over sequence length and ending rank fits this?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP over position and rank with cumulative sums handles D/I transition ranges efficiently.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc906-super-palindromes-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 906 - Super Palindromes', fullProblem: 'Count numbers in [left,right] that are palindromes and whose square roots are also palindromes.', io: 'Input: left and right as strings. Output: count of super-palindromes.', constraints: 'Need generate palindromic roots within bounds and verify squared values.', objective: 'Which pattern uses answer-space boundary reasoning to limit candidate generation?' }), correctPattern: 'Binary Search on Answer Space', correctExplanation: 'Constrain palindrome root range via sqrt bounds and test generated candidates within numeric interval.',
  }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc913-cat-and-mouse-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 913 - Cat and Mouse', fullProblem: 'In graph game, mouse and cat move alternately. Mouse starts at 1, cat at 2, mouse tries reach hole 0, cat tries catch mouse. Determine game outcome under optimal play.', io: 'Input: graph adjacency list. Output: 0 draw, 1 mouse win, 2 cat win.', constraints: 'Need retrograde state resolution with out-degree dependencies.', objective: 'Which graph-state propagation pattern resolves outcomes in reverse topological fashion?' }), correctPattern: "Topological Sort (Kahn's Algorithm - Indegree BFS)", correctExplanation: 'Retrograde analysis uses queue of decided states and propagates forced wins/losses via remaining move counts.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc920-number-of-music-playlists-additional-14', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 920 - Number of Music Playlists', fullProblem: 'Create playlist length goal from n unique songs where each song appears at least once and a song can repeat only after k other songs played. Count playlists modulo mod.', io: 'Input: n, goal, k. Output: number of valid playlists modulo mod.', constraints: 'Need combinational DP over playlist length and distinct songs used.', objective: 'Which dynamic programming pattern over 2D state space applies?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP[length][used] transitions by adding new song or replaying eligible existing song count.',
  }),
]

export default data
