import { buildLeetcodePatternQuestion } from '../patternOptions'

function richPrompt(params: {
  title: string
  fullProblem: string
  io: string
  constraints: string
  objective: string
}): string {
  return (
    `${params.title}\n\n` +
    `Full Problem Statement: ${params.fullProblem}\n` +
    `Input/Output Requirements: ${params.io}\n` +
    `Constraints and Edge Cases: ${params.constraints}\n\n` +
    `Pattern Selection Question: ${params.objective}`
  )
}

const data = [
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1096-brace-expansion-ii-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1096 - Brace Expansion II', fullProblem: 'Given expression with braces representing unions and concatenations of string sets, return all expanded strings sorted and unique.', io: 'Input: expression string. Output: sorted unique expanded strings.', constraints: 'Need parse nested grammar and combine sets with precedence.', objective: 'Which stack-based parsing pattern manages nested expression contexts and operators?' }), correctPattern: 'Monotonic Stack', correctExplanation: 'Use recursive descent or stacks to parse unions/concats and combine intermediate sets correctly.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1106-parsing-a-boolean-expression-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1106 - Parsing A Boolean Expression', fullProblem: 'Evaluate boolean expression containing t,f,!,&,| and nested parentheses.', io: 'Input: expression string. Output: boolean result.', constraints: 'Need nested operator scopes and multi-operand reductions.', objective: 'Which stack evaluation pattern is best for nested boolean expressions?' }), correctPattern: 'Monotonic Stack', correctExplanation: 'Push tokens until closing parenthesis then reduce segment according to operator and push resulting literal.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1125-smallest-sufficient-team-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1125 - Smallest Sufficient Team', fullProblem: 'Given required skills and people skill sets, return any smallest team covering all required skills.', io: 'Input: req_skills and people skills. Output: list of selected people indices.', constraints: 'Skill coverage is a subset-state optimization.', objective: 'Which subset-state DP pattern over skill masks applies?' }), correctPattern: 'Bitmask DP', correctExplanation: 'DP over skill mask stores minimum team achieving each mask, updating by adding each person mask.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1147-longest-chunked-palindrome-decomposition-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1147 - Longest Chunked Palindrome Decomposition', fullProblem: 'Split string into maximum number of non-empty chunks such that i-th chunk from start equals i-th chunk from end.', io: 'Input: text string. Output: maximum chunk count.', constraints: 'Need two-side matching growth and recursive decomposition.', objective: 'Which opposite-direction pointer pattern compares growing prefix/suffix chunks?' }), correctPattern: 'Two Pointers (Opposite Direction)', correctExplanation: 'Grow prefix and suffix pointers inward and split whenever equal chunk strings are formed.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1157-online-majority-element-in-subarray-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1157 - Online Majority Element In Subarray', fullProblem: 'Design structure for queries (left,right,threshold) returning element appearing at least threshold times in subarray or -1.', io: 'Input: nums and many online queries. Output: majority candidate or -1 per query.', constraints: 'Need fast range frequency verification and candidate retrieval.', objective: 'Which range-query tree pattern supports efficient candidate aggregation and checking?' }), correctPattern: 'Segment Tree', correctExplanation: 'Segment tree stores majority-like candidates, then candidate frequency checked via index lists/binary searches.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1172-dinner-plate-stacks-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1172 - Dinner Plate Stacks', fullProblem: 'Design stacks with fixed capacity supporting push, pop, and popAtStack(index) while filling leftmost available stack on push.', io: 'Input: sequence of operations. Output: returned values from pops.', constraints: 'Need track leftmost non-full and rightmost non-empty stacks efficiently.', objective: 'Which top-k/priority structure pattern tracks candidate stack indices?' }), correctPattern: 'Top K Elements', correctExplanation: 'Use min-heap for available stacks and max pointer/heap for non-empty stacks to route operations efficiently.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1192-critical-connections-in-a-network-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1192 - Critical Connections in a Network', fullProblem: 'Find all bridges in undirected connected graph where removing edge disconnects graph.', io: 'Input: n nodes and edges. Output: list of bridge edges.', constraints: 'Need linear-time low-link discovery values.', objective: 'Which SCC/low-link algorithm family identifies bridges?' }), correctPattern: "Tarjan's / Kosaraju's Algorithm", correctExplanation: 'Tarjan DFS computes discovery and low-link values; edge u-v is bridge when low[v] > disc[u].' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1220-count-vowels-permutation-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1220 - Count Vowels Permutation', fullProblem: 'Count strings of length n consisting of vowels with specified follow rules between vowels.', io: 'Input: n. Output: count modulo mod.', constraints: 'Finite-state transitions repeated n times.', objective: 'Which DP pattern over small state machine transition graph applies?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'Track count ending in each vowel per length and update via transition rules each step.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1239-maximum-length-of-a-concatenated-string-with-unique-characters-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1239 - Maximum Length of a Concatenated String with Unique Characters', fullProblem: 'Choose subset/order of strings to maximize concatenated length with all unique chars.', io: 'Input: arr strings. Output: max possible unique-char concatenation length.', constraints: 'Need subset exploration with bitmask conflict pruning.', objective: 'Which bitmask-state search pattern best represents chosen character sets?' }), correctPattern: 'Bitmask DP', correctExplanation: 'Represent each string as char mask and combine only disjoint masks while maximizing set bit count.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1240-tiling-a-rectangle-with-the-fewest-squares-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1240 - Tiling a Rectangle with the Fewest Squares', fullProblem: 'Tile n x m rectangle using integer-sided squares minimizing number of squares.', io: 'Input: n and m. Output: minimum square count.', constraints: 'Search space huge; need profile-state pruning and best-first cut strategies.', objective: 'Which pattern performs strong pruning in recursive placement search?' }), correctPattern: 'Pruning and Constraint Propagation', correctExplanation: 'Backtracking with skyline/state compression and branch-and-bound prunes suboptimal tilings early.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1274-number-of-ships-in-a-rectangle-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1274 - Number of Ships in a Rectangle', fullProblem: 'Using Sea API hasShips(topRight,bottomLeft), count ships in rectangle with at most 10 ships and limited API calls.', io: 'Input: rectangle bounds with black-box API. Output: exact ship count.', constraints: 'Need recursive spatial partitioning and pruning when API says empty.', objective: 'Which divide-and-conquer search pattern with pruning constraints fits?' }), correctPattern: 'Pruning and Constraint Propagation', correctExplanation: 'Recursively split region into quadrants and prune branches where hasShips is false.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1298-maximum-candies-you-can-get-from-boxes-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1298 - Maximum Candies You Can Get from Boxes', fullProblem: 'Boxes may be open/closed, contain candies, keys, and other boxes. Starting with initial boxes, maximize candies collectable.', io: 'Input: status, candies, keys, containedBoxes, initialBoxes. Output: maximum candies.', constraints: 'Need iterative reachability as keys unlock deferred boxes.', objective: 'Which graph traversal pattern over evolving reachable/open states works best?' }), correctPattern: 'Graph BFS (Shortest Path in Unweighted Graph)', correctExplanation: 'Queue process open boxes, accumulate keys and newly accessible boxes, revisiting when status changes.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1301-number-of-paths-with-max-score-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1301 - Number of Paths with Max Score', fullProblem: 'From S to E in grid moving up/left/diag, maximize collected score and count number of max-score paths.', io: 'Input: board grid. Output: [maxScore, count] modulo mod.', constraints: 'Need joint optimization of best score and path counts.', objective: 'Which grid DP pattern tracks both best value and number of ways?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP cell stores max score achievable to end and number of ways achieving that max.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1345-jump-game-iv-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1345 - Jump Game IV', fullProblem: 'From index 0, you can jump to i-1, i+1, and any j where arr[j]==arr[i]. Find minimum jumps to last index.', io: 'Input: arr. Output: minimum jump count.', constraints: 'Need avoid repeated expansion of same-value index groups.', objective: 'Which unweighted shortest-path pattern solves this with level traversal and value-group pruning?' }), correctPattern: 'Graph BFS (Shortest Path in Unweighted Graph)', correctExplanation: 'BFS over indices with map value->indices; clear processed value groups to avoid repeated O(n^2) expansions.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1363-largest-multiple-of-three-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1363 - Largest Multiple of Three', fullProblem: 'Given digits, form largest possible number that is multiple of 3, or empty if impossible.', io: 'Input: digits array. Output: largest valid number string.', constraints: 'Need remove minimal-impact digits to satisfy sum mod 3.', objective: 'Which counting/hash pattern over digit frequencies is appropriate?' }), correctPattern: 'In-place Array Hashing / Marking', correctExplanation: 'Count digits by value, adjust by removing smallest needed mod-group digits, then output descending digits.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1373-maximum-sum-bst-in-binary-tree-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1373 - Maximum Sum BST in Binary Tree', fullProblem: 'Find maximum sum of values of any subtree that is also a valid BST.', io: 'Input: binary tree root. Output: maximum BST subtree sum.', constraints: 'Need subtree metadata propagation: min, max, sum, and BST validity.', objective: 'Which tree DP pattern computes composite subtree state bottom-up?' }), correctPattern: 'DP on Trees', correctExplanation: 'Postorder returns subtree stats and validity; valid BST subtrees update global maximum sum.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1406-stone-game-iii-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1406 - Stone Game III', fullProblem: 'Players take 1-3 stones from front with optimal play maximizing score difference. Return winner or tie.', io: 'Input: stoneValue array. Output: Alice, Bob, or Tie.', constraints: 'Need suffix game-state value differences.', objective: 'Which linear DP pattern over index computes best score differential?' }), correctPattern: '1D DP (Fibonacci / Climbing Stairs Pattern)', correctExplanation: 'DP[i] is max score diff current player can enforce from i by choosing 1..3 stones.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1420-build-array-where-you-can-find-the-maximum-exactly-k-comparisons-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1420 - Build Array Where You Can Find The Maximum Exactly K Comparisons', fullProblem: 'Count arrays length n with values 1..m such that scanning left to right updates running maximum exactly k times.', io: 'Input: n, m, k. Output: count modulo mod.', constraints: 'Need 3D state over length, current max, and search cost.', objective: 'Which multidimensional DP pattern is required?' }), correctPattern: 'Matrix / Grid DP', correctExplanation: 'DP[len][maxVal][cost] transitions by appending value <= max or introducing new max with cost+1.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1458-max-dot-product-of-two-subsequences-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1458 - Max Dot Product of Two Subsequences', fullProblem: 'Find maximum dot product between non-empty subsequences from two arrays.', io: 'Input: nums1 and nums2. Output: maximum dot product.', constraints: 'Need 2D DP with include/skip transitions and non-empty enforcement.', objective: 'Which two-sequence DP family akin LCS but with weighted value transitions applies?' }), correctPattern: 'Longest Common Subsequence (LCS) Pattern', correctExplanation: 'DP over i,j decides take pair i,j (possibly starting fresh) or skip one side, similar to LCS table structure.' }),
  buildLeetcodePatternQuestion({ id: 'leetcode-pattern-type-hard-lc1478-allocate-mailboxes-additional-16', difficulty: 'hard', prompt: richPrompt({ title: 'LeetCode 1478 - Allocate Mailboxes', fullProblem: 'Place k mailboxes for house positions to minimize sum of distances from each house to nearest mailbox.', io: 'Input: houses array and k. Output: minimum total distance.', constraints: 'Need precomputed segment costs and partition DP over sorted houses.', objective: 'Which interval/substructure DP pattern best models partitioning into k groups?' }), correctPattern: 'Palindromic Substring / Subsequence DP', correctExplanation: 'Precompute median-based cost for any interval, then DP over prefix and mailbox count for optimal partitions.' }),
]

export default data
