import { buildLeetcodePatternQuestion } from '../patternOptions'

function richPrompt(params: {
  title: string
  fullProblem: string
  io: string
  constraints: string
  objective: string
}): string {
  return (
    `${params.title}\n\n` +
    `Full Problem Statement: ${params.fullProblem}\n` +
    `Input/Output Requirements: ${params.io}\n` +
    `Constraints and Edge Cases: ${params.constraints}\n\n` +
    `Pattern Selection Question: ${params.objective}`
  )
}

const data = [
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc4-median-two-sorted-arrays-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 4 - Median of Two Sorted Arrays',
      fullProblem: 'Given two sorted arrays nums1 and nums2 of lengths m and n, return the median of the two sorted arrays. The overall run time complexity must be O(log(m+n)).',
      io: 'Input: two sorted integer arrays. Output: median value as number.',
      constraints: 'Need logarithmic selection logic; direct merge to full array is too slow for strict complexity target.',
      objective: 'Which pattern is best for boundary search over sorted partitions to locate median split?',
    }),
    correctPattern: 'Binary Search for Boundary / First-Last Occurrence',
    correctExplanation: 'Binary search partition index in smaller array, validating left/right boundary conditions across both arrays.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc10-regular-expression-matching-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 10 - Regular Expression Matching',
      fullProblem: 'Implement regular expression matching with support for dot and star where dot matches any single character and star matches zero or more of the preceding element. Matching must cover entire string.',
      io: 'Input: string s and pattern p. Output: boolean full-match result.',
      constraints: 'Local decisions interact globally because star can absorb variable lengths.',
      objective: 'Which two-sequence dynamic programming pattern best fits full-string match states?',
    }),
    correctPattern: 'Longest Common Subsequence (LCS) Pattern',
    correctExplanation: 'A 2D DP over indices of s and p handles transitions for direct match, dot match, and star expansion/skips.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc23-merge-k-sorted-lists-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 23 - Merge k Sorted Lists',
      fullProblem: 'Merge k sorted linked lists and return one sorted linked list containing all nodes.',
      io: 'Input: array of k sorted list heads. Output: merged sorted list head.',
      constraints: 'Need to repeatedly extract current minimum among k list fronts efficiently.',
      objective: 'Which pattern is designed for merging many sorted streams simultaneously?',
    }),
    correctPattern: 'K-Way Merge',
    correctExplanation: 'Use a min-heap keyed by current node value from each list to build merged order incrementally.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc25-reverse-nodes-in-k-group-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 25 - Reverse Nodes in k-Group',
      fullProblem: 'Given linked list head, reverse nodes in groups of size k and return modified list. If final group has fewer than k nodes, leave it unchanged.',
      io: 'Input: linked list head and integer k. Output: updated head after grouped reversals.',
      constraints: 'Need pointer-safe in-place rewiring with segment boundaries and reconnect logic.',
      objective: 'Which linked-list pattern focuses on in-place reversal of bounded segments?',
    }),
    correctPattern: 'In-place Linked List Reversal',
    correctExplanation: 'Reverse each complete k-node block in place, then reconnect block tails/heads across segments.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc30-substring-with-concatenation-of-all-words-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 30 - Substring with Concatenation of All Words',
      fullProblem: 'Given string s and list words of equal length, find all start indices where concatenation of each word exactly once and without separators appears.',
      io: 'Input: s and words. Output: list of valid starting indices.',
      constraints: 'Need frequency-balanced matching across fixed total window size with word-aligned steps.',
      objective: 'Which pattern scans fixed-length windows while maintaining rolling token counts?',
    }),
    correctPattern: 'Sliding Window (Fixed Size)',
    correctExplanation: 'Use window length = wordLen * wordCount and maintain per-word counts while sliding by wordLen offsets.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc32-longest-valid-parentheses-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 32 - Longest Valid Parentheses',
      fullProblem: 'Given a string containing only parentheses, return length of the longest well-formed valid parentheses substring.',
      io: 'Input: parentheses string. Output: maximum valid substring length.',
      constraints: 'Need linear-time boundary tracking of unmatched positions.',
      objective: 'Which pattern uses stack-index state to pair delimiters and compute span lengths?',
    }),
    correctPattern: 'Monotonic Stack',
    correctExplanation: 'Stack of indices tracks unmatched boundaries; valid matches compute current length against latest invalid index.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc37-sudoku-solver-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 37 - Sudoku Solver',
      fullProblem: 'Fill a partially completed 9x9 Sudoku board so that every row, column, and 3x3 sub-box contains digits 1 to 9 exactly once.',
      io: 'Input: mutable 9x9 board with digits and dots. Output: board solved in place.',
      constraints: 'Need systematic search with aggressive constraint checks to avoid combinational explosion.',
      objective: 'Which pattern emphasizes backtracking with pruning from row/column/box constraints?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Backtrack over empty cells and prune branches immediately when candidate violates Sudoku constraints.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc41-first-missing-positive-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 41 - First Missing Positive',
      fullProblem: 'Given unsorted integer array, find smallest missing positive integer in O(n) time and O(1) extra space.',
      io: 'Input: integer array nums. Output: smallest missing positive integer.',
      constraints: 'Need in-place index placement/marking strategy; sorting or extra hash sets break constraints.',
      objective: 'Which pattern positions values to their intended index slots to reveal missing index?',
    }),
    correctPattern: 'Cyclic Sort',
    correctExplanation: 'Place value v at index v-1 when possible; first index mismatch indicates missing positive.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc44-wildcard-matching-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 44 - Wildcard Matching',
      fullProblem: 'Implement wildcard pattern matching with question mark matching any single char and star matching any sequence including empty. Entire string must be matched.',
      io: 'Input: string s and pattern p. Output: boolean full-match result.',
      constraints: 'Need to handle large ambiguous star expansions efficiently via dynamic state transitions.',
      objective: 'Which two-sequence DP pattern over prefix states is appropriate here?',
    }),
    correctPattern: 'Matrix / Grid DP',
    correctExplanation: 'DP table across s and p indices handles direct match, question match, and star consume/skip transitions.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc51-n-queens-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 51 - N-Queens',
      fullProblem: 'Place n queens on an n x n chessboard such that no two queens attack each other and return all valid board configurations.',
      io: 'Input: integer n. Output: list of all distinct valid board layouts.',
      constraints: 'Need branch pruning using occupied columns and diagonals to avoid factorial blowup.',
      objective: 'Which pattern searches row-by-row with strong constraint propagation?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Backtracking with column and diagonal occupancy checks prunes invalid branches early.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc52-n-queens-ii-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 52 - N-Queens II',
      fullProblem: 'Return total number of distinct ways to place n queens on an n x n board so that no queen attacks another.',
      io: 'Input: integer n. Output: count of valid configurations.',
      constraints: 'Same combinational search space as N-Queens but only count is required.',
      objective: 'Which pattern performs constrained backtracking with occupancy pruning?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Use backtracking with conflict checks on columns and diagonals; increment count on full placement.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc68-text-justification-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 68 - Text Justification',
      fullProblem: 'Given words and maxWidth, arrange text so each line has exactly maxWidth chars with fully justified spacing except last line left-justified.',
      io: 'Input: words array and maxWidth. Output: list of justified lines.',
      constraints: 'Need greedy line packing and deterministic space distribution across gaps.',
      objective: 'Which pattern fits forward scanning with line start/end pointers and in-line redistribution logic?',
    }),
    correctPattern: 'Two Pointers (Same Direction / Fast and Slow)',
    correctExplanation: 'Advance end pointer to pack words per line, then format spacing using start/end line boundaries.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc72-edit-distance-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 72 - Edit Distance',
      fullProblem: 'Given two strings, return minimum number of operations (insert, delete, replace) to transform one string into the other.',
      io: 'Input: word1 and word2. Output: minimum edit operation count.',
      constraints: 'Each operation changes future alignment, requiring global optimization over prefixes.',
      objective: 'Which classic two-string dynamic programming pattern applies here?',
    }),
    correctPattern: 'Longest Common Subsequence (LCS) Pattern',
    correctExplanation: '2D DP over prefix pairs models insertion, deletion, and replacement transitions to minimize edits.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc87-scramble-string-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 87 - Scramble String',
      fullProblem: 'Determine whether s2 is a scrambled string of s1 by recursively partitioning and optionally swapping child substrings.',
      io: 'Input: strings s1 and s2. Output: boolean indicating scramble equivalence.',
      constraints: 'Need partition-based subproblem memoization due high overlap in recursive checks.',
      objective: 'Which interval-style DP pattern over substring ranges is most appropriate?',
    }),
    correctPattern: 'Palindromic Substring / Subsequence DP',
    correctExplanation: 'Interval DP/memoization over substring ranges and split points avoids exponential recomputation.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc97-interleaving-string-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 97 - Interleaving String',
      fullProblem: 'Given strings s1, s2, s3, determine if s3 is formed by interleaving s1 and s2 while preserving relative order of chars from each source string.',
      io: 'Input: s1, s2, s3. Output: boolean interleaving validity.',
      constraints: 'Need paired index state over s1 and s2 with implied index in s3.',
      objective: 'Which 2D grid-style DP over source prefixes matches this state structure?',
    }),
    correctPattern: 'Matrix / Grid DP',
    correctExplanation: 'DP[i][j] indicates whether s1 prefix i and s2 prefix j can form s3 prefix i+j.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc126-word-ladder-ii-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 126 - Word Ladder II',
      fullProblem: 'Find all shortest transformation sequences from beginWord to endWord, changing one letter at a time and using only dictionary words.',
      io: 'Input: beginWord, endWord, wordList. Output: list of all shortest sequences.',
      constraints: 'Need shortest-level discovery before path reconstruction to avoid longer sequences.',
      objective: 'Which pattern discovers shortest distances in unweighted word graph layers?',
    }),
    correctPattern: 'Graph BFS (Shortest Path in Unweighted Graph)',
    correctExplanation: 'BFS builds shortest-level parent graph; DFS/backtracking over parent links reconstructs all shortest paths.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc135-candy-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 135 - Candy',
      fullProblem: 'Children stand in a line with ratings. Give candies so each child has at least one candy and higher-rated child than a neighbor gets more candies. Minimize total candies.',
      io: 'Input: ratings array. Output: minimum total candies.',
      constraints: 'Need satisfy constraints from both left and right neighbors.',
      objective: 'Which pattern uses directional passes and cumulative reconciliation of local constraints?',
    }),
    correctPattern: 'Prefix Sum / Cumulative Sum',
    correctExplanation: 'Left-to-right and right-to-left passes compute required minima, then combine per index and sum.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc140-word-break-ii-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 140 - Word Break II',
      fullProblem: 'Given string s and dictionary wordDict, return all possible sentences where spaces split s into valid dictionary words.',
      io: 'Input: s and wordDict. Output: list of all valid segmented sentences.',
      constraints: 'Need recursive branching with memoization/pruning to avoid combinational explosion.',
      objective: 'Which pattern combines backtracking with strong feasibility pruning and memoized suffix results?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Backtrack over cut points, prune impossible suffixes, and memoize results by index.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc164-maximum-gap-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 164 - Maximum Gap',
      fullProblem: 'Given unsorted array, return maximum difference between successive elements in sorted form in linear time and space if possible.',
      io: 'Input: nums array. Output: maximum adjacent sorted gap.',
      constraints: 'Need avoid O(n log n) explicit sort in strict variant; bucket/indexed placement ideas are key.',
      objective: 'Which pattern relies on bucket-style indexing/marking to recover ordered gap information?',
    }),
    correctPattern: 'In-place Array Hashing / Marking',
    correctExplanation: 'Bucket placement based on value range tracks local mins/maxes and enables linear max-gap extraction.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc174-dungeon-game-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 174 - Dungeon Game',
      fullProblem: 'Knight moves only right or down in dungeon grid with health gain/loss cells. Find minimum initial health so knight can rescue princess and never drop to 0 or below.',
      io: 'Input: dungeon matrix. Output: minimum starting health integer.',
      constraints: 'Optimal requirement at each cell depends on future path requirements, suggesting reverse DP.',
      objective: 'Which grid dynamic programming pattern computes required health backward from destination?',
    }),
    correctPattern: 'Matrix / Grid DP',
    correctExplanation: 'DP from bottom-right computes minimum health needed to enter each cell and survive onward.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc214-shortest-palindrome-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 214 - Shortest Palindrome',
      fullProblem: 'Given string s, prepend characters to make it a palindrome with minimum added characters and return resulting shortest palindrome.',
      io: 'Input: string s. Output: shortest palindrome formed by adding chars in front.',
      constraints: 'Need efficiently find longest palindromic prefix.',
      objective: 'Which cumulative-prefix style pattern helps detect reusable prefix/suffix structure quickly?',
    }),
    correctPattern: 'Prefix Sum / Cumulative Sum',
    correctExplanation: 'Prefix-function style cumulative matching over s + separator + reverse(s) identifies longest palindromic prefix.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc218-the-skyline-problem-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 218 - The Skyline Problem',
      fullProblem: 'Given building rectangles, output key points forming city skyline silhouette.',
      io: 'Input: buildings as [left,right,height]. Output: ordered key points [x,height].',
      constraints: 'Need process many start/end events and track active maximum height dynamically.',
      objective: 'Which event-processing interval pattern is designed for boundary transitions over coordinates?',
    }),
    correctPattern: 'Sweep Line Algorithm / Interval Boundary Events',
    correctExplanation: 'Sort building boundary events by x and maintain active heights to emit skyline changes.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc224-basic-calculator-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 224 - Basic Calculator',
      fullProblem: 'Evaluate arithmetic expression string containing integers, plus, minus, parentheses, and spaces.',
      io: 'Input: expression string. Output: evaluated integer result.',
      constraints: 'Need nested context handling for parentheses with sign propagation.',
      objective: 'Which pattern manages nested expression states with LIFO context storage?',
    }),
    correctPattern: 'Monotonic Stack',
    correctExplanation: 'Use stack to save previous result/sign context when entering parentheses and restore on close.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc233-number-of-digit-one-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 233 - Number of Digit One',
      fullProblem: 'Count total occurrences of digit 1 appearing in all non-negative integers less than or equal to n.',
      io: 'Input: integer n. Output: total count of digit one occurrences.',
      constraints: 'Need positional decomposition by powers of ten rather than iterating each number.',
      objective: 'Which dynamic counting pattern over digit positions best structures this solution?',
    }),
    correctPattern: '1D DP (Fibonacci / Climbing Stairs Pattern)',
    correctExplanation: 'Process each decimal place with higher/current/lower decomposition and accumulate contributions.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc248-strobogrammatic-number-iii-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 248 - Strobogrammatic Number III',
      fullProblem: 'Given two strings low and high, count strobogrammatic numbers within inclusive range [low, high].',
      io: 'Input: low and high as strings. Output: count of valid strobogrammatic numbers in range.',
      constraints: 'Need generate candidate numbers by mirrored digit pairs while pruning by length/range.',
      objective: 'Which pattern centers on recursive construction with constraint pruning?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Build numbers from both ends using valid strobogrammatic pairs and prune candidates outside range constraints.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc273-integer-to-english-words-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 273 - Integer to English Words',
      fullProblem: 'Convert non-negative integer into its English words representation.',
      io: 'Input: integer num. Output: English phrase string.',
      constraints: 'Need hierarchical decomposition by billions, millions, thousands, and hundreds.',
      objective: 'Which recursive decomposition pattern over number tree-like segments is most suitable?',
    }),
    correctPattern: 'Tree DFS (Pre-order)',
    correctExplanation: 'Recursively decompose high-order chunks first and append segment words in top-down order.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc282-expression-add-operators-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 282 - Expression Add Operators',
      fullProblem: 'Given numeric string num and target, insert operators plus, minus, multiply between digits to form expressions that evaluate to target.',
      io: 'Input: num string and target integer. Output: list of valid expression strings.',
      constraints: 'Need exhaustive expression generation with pruning and careful multiplication precedence tracking.',
      objective: 'Which pattern performs constrained backtracking over operator insertion choices?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Backtracking enumerates split/operator choices while carrying running value and last multiplicative term.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc302-smallest-rectangle-enclosing-black-pixels-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 302 - Smallest Rectangle Enclosing Black Pixels',
      fullProblem: 'Given binary image with one connected black region and one black pixel location, find area of smallest axis-aligned rectangle enclosing all black pixels.',
      io: 'Input: image and one black pixel coordinate. Output: enclosing rectangle area.',
      constraints: 'Need discover region boundaries efficiently via graph traversal or boundary search.',
      objective: 'Which pattern traverses connected component to collect min/max row and column bounds?',
    }),
    correctPattern: 'Graph DFS (Connected Components / Path Finding)',
    correctExplanation: 'DFS/BFS from known black pixel visits all connected black pixels and tracks bounding coordinates.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc308-range-sum-query-2d-mutable-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 308 - Range Sum Query 2D - Mutable',
      fullProblem: 'Design data structure supporting update(row,col,val) and sumRegion queries on mutable 2D matrix.',
      io: 'Input: sequence of updates and rectangular sum queries. Output: sum results for query calls.',
      constraints: 'Need sublinear updates and queries compared with full matrix rescans.',
      objective: 'Which indexed tree pattern supports efficient prefix/range aggregation with updates?',
    }),
    correctPattern: 'Fenwick Tree (Binary Indexed Tree / BIT)',
    correctExplanation: '2D BIT supports logarithmic point updates and rectangular prefix-sum composition for region queries.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc316-remove-duplicate-letters-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 316 - Remove Duplicate Letters',
      fullProblem: 'Given string s, remove duplicate letters so each letter appears once and result is smallest in lexicographical order among all valid results.',
      io: 'Input: string s. Output: lexicographically smallest string with unique letters.',
      constraints: 'Need preserve relative order opportunities while greedily selecting smaller available chars.',
      objective: 'Which monotonic structure pattern greedily maintains smallest feasible character stack?',
    }),
    correctPattern: 'Monotonic Stack',
    correctExplanation: 'Use stack with last-occurrence info; pop larger chars if they appear later and current char is smaller.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc321-create-maximum-number-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 321 - Create Maximum Number',
      fullProblem: 'From two arrays of digits, create maximum number of length k by selecting subsequences from each array while preserving order within each source.',
      io: 'Input: nums1, nums2, k. Output: lexicographically maximum digit sequence length k.',
      constraints: 'Need optimal subsequence extraction and merge comparisons across split sizes.',
      objective: 'Which pattern is used to extract maximum subsequence from each array under length constraint?',
    }),
    correctPattern: 'Monotonic Stack',
    correctExplanation: 'Greedy monotonic stack extracts best subsequence for each length; then merge with lexicographic tie handling.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc327-count-of-range-sum-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 327 - Count of Range Sum',
      fullProblem: 'Count number of range sums S(i,j) in array nums such that lower <= S(i,j) <= upper.',
      io: 'Input: nums, lower, upper. Output: count of valid range sums.',
      constraints: 'Need faster than O(n^2); range sums are differences of prefix sums.',
      objective: 'Which pattern reframes subarray sums through cumulative prefixes and bounded difference counting?',
    }),
    correctPattern: 'Prefix Sum / Cumulative Sum',
    correctExplanation: 'Build prefix sums and count pairs of prefixes whose differences lie within [lower, upper].',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc330-patching-array-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 330 - Patching Array',
      fullProblem: 'Given sorted nums and n, add minimum numbers so every number in [1,n] can be formed as sum of some subset.',
      io: 'Input: nums and n. Output: minimum count of patches required.',
      constraints: 'Need greedy coverage extension logic over representable prefix range.',
      objective: 'Which cumulative coverage pattern tracks largest continuous representable range and extends it optimally?',
    }),
    correctPattern: 'Prefix Sum / Cumulative Sum',
    correctExplanation: 'Maintain current reachable range [1, miss); consume nums[i] when <= miss, else patch with miss to double coverage.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc332-reconstruct-itinerary-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 332 - Reconstruct Itinerary',
      fullProblem: 'Given airline tickets [from,to], reconstruct itinerary starting at JFK using all tickets exactly once; if multiple, return lexicographically smallest.',
      io: 'Input: ticket pairs. Output: itinerary airport sequence.',
      constraints: 'Need edge-usage traversal akin Eulerian path with lexical ordering.',
      objective: 'Which graph traversal pattern recursively consumes edges and backtracks into final route order?',
    }),
    correctPattern: 'Graph DFS (Connected Components / Path Finding)',
    correctExplanation: 'Hierholzer-style DFS consumes outgoing edges in lexical order and appends nodes postorder to build itinerary.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc335-self-crossing-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 335 - Self Crossing',
      fullProblem: 'Given movement distances in repeating directions north-west-south-east, determine if path crosses itself.',
      io: 'Input: distance array. Output: boolean self-crossing indicator.',
      constraints: 'Need O(1) extra space geometric condition checks against recent segments.',
      objective: 'Which directional pointer progression pattern checks local crossing configurations in one pass?',
    }),
    correctPattern: 'Two Pointers (Same Direction / Fast and Slow)',
    correctExplanation: 'Evaluate crossing conditions involving current segment and a bounded window of previous segments while scanning forward.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc352-data-stream-as-disjoint-intervals-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 352 - Data Stream as Disjoint Intervals',
      fullProblem: 'Design SummaryRanges data structure supporting addNum and returning sorted disjoint intervals of all seen numbers.',
      io: 'Input: online insertions. Output: current disjoint interval list after updates.',
      constraints: 'Need dynamic interval merge of neighbors on insertion.',
      objective: 'Which interval boundary-event pattern is used to maintain disjoint merged ranges online?',
    }),
    correctPattern: 'Sweep Line Algorithm / Interval Boundary Events',
    correctExplanation: 'Each insertion potentially bridges adjacent intervals; maintain ordered boundaries and merge overlap/adjacency.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc358-rearrange-string-k-distance-apart-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 358 - Rearrange String k Distance Apart',
      fullProblem: 'Rearrange string so same characters are at least k distance apart, or return empty string if impossible.',
      io: 'Input: string s and integer k. Output: valid rearranged string or empty.',
      constraints: 'Need repeatedly place currently most frequent feasible characters while honoring cooldown gaps.',
      objective: 'Which pattern repeatedly extracts top-priority counts under spacing constraints?',
    }),
    correctPattern: 'Top K Frequent Elements',
    correctExplanation: 'Use max-heap by frequency with cooldown queue to reinsert chars when eligible again.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc381-insert-delete-getrandom-o1-duplicates-allowed-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 381 - Insert Delete GetRandom O(1) - Duplicates allowed',
      fullProblem: 'Design collection supporting insert, remove, and getRandom in average O(1) while allowing duplicate values.',
      io: 'Input: sequence of operations. Output: operation results, especially random retrieval from current multiset.',
      constraints: 'Need indexable array plus value-to-index-set mapping for O(1) deletion swaps.',
      objective: 'Which hashing/index-marking pattern enables constant-time updates with duplicates?',
    }),
    correctPattern: 'In-place Array Hashing / Marking',
    correctExplanation: 'Maintain dynamic array plus hash map from value to index set; swap-remove keeps operations O(1) average.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc391-perfect-rectangle-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 391 - Perfect Rectangle',
      fullProblem: 'Given axis-aligned rectangles, determine if they exactly cover one rectangular region with no overlaps and no gaps.',
      io: 'Input: list of rectangles. Output: boolean perfect cover result.',
      constraints: 'Need area consistency and corner parity/boundary-event validation.',
      objective: 'Which interval/sweep-line style boundary accounting pattern best checks global cover correctness?',
    }),
    correctPattern: 'Sweep Line Algorithm / Interval Boundary Events',
    correctExplanation: 'Combine total area check with corner occurrence parity to validate exact boundary composition.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc403-frog-jump-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 403 - Frog Jump',
      fullProblem: 'Frog starts at first stone and can jump k-1, k, or k+1 if last jump was k. Determine if frog can reach last stone.',
      io: 'Input: sorted stone positions. Output: boolean reachability to final stone.',
      constraints: 'Need state on stone index/position and last jump size with memoization.',
      objective: 'Which sequential state dynamic programming pattern captures jump-size transitions?',
    }),
    correctPattern: '1D DP (Fibonacci / Climbing Stairs Pattern)',
    correctExplanation: 'Memoized state by (stone, lastJump) explores allowed next jump sizes without recomputation.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc411-minimum-unique-word-abbreviation-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 411 - Minimum Unique Word Abbreviation',
      fullProblem: 'Given target word and dictionary, find shortest abbreviation of target that does not conflict with abbreviations of any dictionary word of same length.',
      io: 'Input: target and dictionary. Output: shortest unique abbreviation string.',
      constraints: 'Need combinational search over abbreviation masks with conflict pruning.',
      objective: 'Which pattern uses aggressive branch pruning under mask-based constraints?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Enumerate abbreviation masks and prune by length/conflict conditions to find shortest valid candidate.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc420-strong-password-checker-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 420 - Strong Password Checker',
      fullProblem: 'Return minimum number of edits (insert, delete, replace) required to make password strong under length, character-class, and repetition rules.',
      io: 'Input: password string. Output: minimum edit count.',
      constraints: 'Need case-by-case optimization blending replacement needs with deletions for long repeated runs.',
      objective: 'Which pattern uses constraint-driven optimization with branch-specific pruning logic?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Greedy/constraint analysis over run lengths and missing classes minimizes operations across length regimes.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc432-all-oone-data-structure-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 432 - All O`one Data Structure',
      fullProblem: 'Design data structure supporting inc, dec, getMaxKey, and getMinKey in O(1) average time.',
      io: 'Input: sequence of key updates and max/min queries. Output: requested keys for max/min operations.',
      constraints: 'Need key lookup plus ordered frequency buckets with O(1) relocation.',
      objective: 'Which cache-like bucketed frequency pattern best matches this design?',
    }),
    correctPattern: 'LFU Cache',
    correctExplanation: 'Doubly linked frequency buckets with hash maps mirror LFU-style key-to-frequency-node management.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc440-k-th-smallest-in-lexicographical-order-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 440 - K-th Smallest in Lexicographical Order',
      fullProblem: 'Given integers n and k, return the k-th number in lexicographical order from 1 to n.',
      io: 'Input: n and k. Output: integer at lexicographical rank k.',
      constraints: 'Need efficient prefix counting over lexical tree, not explicit enumeration of all values.',
      objective: 'Which prefix-tree style pattern models lexicographical number traversal?',
    }),
    correctPattern: 'Trie (Prefix Tree)',
    correctExplanation: 'Numbers form an implicit trie by decimal prefixes; count subtree sizes to skip or descend.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc466-count-the-repetitions-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 466 - Count The Repetitions',
      fullProblem: 'Given s1 repeated n1 times and s2 repeated n2 times, find maximum integer m such that [s2, n2*m] can be obtained from [s1, n1] via deletion.',
      io: 'Input: s1,n1,s2,n2. Output: maximum m.',
      constraints: 'Need cycle detection over matching progress to avoid simulating every character for huge repeats.',
      objective: 'Which iterative state DP/cycle acceleration pattern best fits repeated-sequence matching?',
    }),
    correctPattern: '1D DP (Fibonacci / Climbing Stairs Pattern)',
    correctExplanation: 'Track progress states across repeated blocks and detect loops to jump counts efficiently.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc483-smallest-good-base-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 483 - Smallest Good Base',
      fullProblem: 'Given integer n as string, find smallest base k >= 2 such that n is represented as all ones in base k.',
      io: 'Input: n as string. Output: smallest valid base as string.',
      constraints: 'Need try possible digit lengths and solve geometric-sum feasibility for each.',
      objective: 'Which pattern binary-searches feasible base values under monotonic geometric sum comparisons?',
    }),
    correctPattern: 'Binary Search on Answer Space',
    correctExplanation: 'For each candidate length, binary search base k and compare geometric series sum to n.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc488-zuma-game-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 488 - Zuma Game',
      fullProblem: 'Given board string and hand balls, insert balls to clear board by removing groups of >=3 same-color consecutive balls. Return minimum insertions or -1.',
      io: 'Input: board and hand strings. Output: minimum steps to clear board or -1.',
      constraints: 'Huge branching requires elimination compression plus memoized recursive search and strong pruning.',
      objective: 'Which pattern focuses on backtracking with state pruning and memoization?',
    }),
    correctPattern: 'Pruning and Constraint Propagation',
    correctExplanation: 'Recursive trial of insertions with chain-reaction reductions and memoized states avoids redundant exploration.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc493-reverse-pairs-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 493 - Reverse Pairs',
      fullProblem: 'Count reverse pairs (i,j) with i<j and nums[i] > 2*nums[j].',
      io: 'Input: nums array. Output: count of reverse pairs.',
      constraints: 'Need faster than quadratic pair enumeration with order-sensitive counting.',
      objective: 'Which boundary-search counting pattern over sorted segments can efficiently count valid j for each i?',
    }),
    correctPattern: 'Binary Search for Boundary / First-Last Occurrence',
    correctExplanation: 'In merge-sort style sorted halves, boundary searches count how many right-side elements satisfy condition per left element.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc499-the-maze-iii-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 499 - The Maze III',
      fullProblem: 'Ball rolls in maze until wall/hole. Find shortest path instructions from start to hole; if tie, lexicographically smallest path.',
      io: 'Input: maze, start, hole. Output: path string or impossible.',
      constraints: 'Edge travel costs vary by roll distance, requiring weighted shortest path with tie-breaking.',
      objective: 'Which weighted shortest-path pattern is appropriate for this rolling maze model?',
    }),
    correctPattern: "Dijkstra's Algorithm",
    correctExplanation: 'Use Dijkstra with state distances by rolled steps and lexical tie handling for equal distances.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-hard-lc514-freedom-trail-additional-13',
    difficulty: 'hard',
    prompt: richPrompt({
      title: 'LeetCode 514 - Freedom Trail',
      fullProblem: 'A circular ring with characters must spell key by rotating left/right and pressing button. Find minimum steps.',
      io: 'Input: ring and key strings. Output: minimum total steps including presses.',
      constraints: 'Need optimize over multiple matching character positions per key index.',
      objective: 'Which dynamic programming pattern over ring position and key index fits best?',
    }),
    correctPattern: 'Matrix / Grid DP',
    correctExplanation: 'DP[keyIndex][ringPos] computes minimum future cost by considering all next matching positions.',
  }),
]

export default data
