const data = [
  {
    id: 'hard-distributed-latency-10-q1',
    difficulty: 'hard',
    prompt: 'A multi-region write path uses quorum. Which change most directly reduces write tail latency without sacrificing durability goals?',
    options: [
      'Wait for all replicas in every region to ack',
      'Use bounded quorum with region-aware replica placement and hedged replica selection',
      'Disable acknowledgements and trust fire-and-forget',
      'Serialize writes behind one global lock',
      'Increase client retries to 10',
      'Convert all writes to async eventual confirmations',
    ],
    correctIndex: 1,
    correctExplanation: 'Region-aware quorum design reduces cross-region tail while preserving correctness guarantees.',
  },
  {
    id: 'hard-distributed-latency-10-q2',
    difficulty: 'hard',
    prompt: 'You observe coordinated omission in latency reports. What is the best correction?',
    options: [
      'Sample fewer requests',
      'Record only successful requests',
      'Use constant-throughput load generation and include delayed-sample accounting',
      'Measure only server-side queue time',
      'Remove warmup periods',
      'Average p95 over hourly windows only',
    ],
    correctIndex: 2,
    correctExplanation: 'Coordinated omission requires workload and measurement fixes that account for blocked periods.',
  },
  {
    id: 'hard-distributed-latency-10-q3',
    difficulty: 'hard',
    prompt: 'An RPC mesh shows retry storms during partial brownouts. Which control set is strongest?',
    options: [
      'No retry limits, rely on autoscaling',
      'Client exponential backoff + retry budgets + circuit breakers + adaptive concurrency',
      'Double default timeouts globally',
      'Drop all 5xx metrics to reduce panic',
      'Route everything to one healthy node',
      'Increase max in-flight requests per upstream endlessly',
    ],
    correctIndex: 1,
    correctExplanation: 'Budgeted retries plus breakers and adaptive concurrency contain feedback loops under brownouts.',
  },
  {
    id: 'hard-distributed-latency-10-q4',
    difficulty: 'hard',
    prompt: 'For a high-fanout aggregator, which strategy best minimizes straggler impact at scale?',
    options: [
      'Wait for strict completion of every branch',
      'Use speculative hedging for slow replicas after a percentile threshold with duplicate suppression',
      'Issue all branch calls sequentially',
      'Disable branch-level deadlines',
      'Increase branch payloads to reduce request count',
      'Pin fanout to one AZ permanently',
    ],
    correctIndex: 1,
    correctExplanation: 'Hedged requests with suppression cuts straggler tails without amplifying duplicate effects excessively.',
  },
  {
    id: 'hard-distributed-latency-10-q5',
    difficulty: 'hard',
    prompt: 'A queue-backed service has unstable latency due to bursty producers. Which architecture move is most robust?',
    options: [
      'Scale consumers only by CPU usage',
      'Introduce admission control, burst absorption limits, and lag-aware autoscaling targets',
      'Disable queue depth alerts',
      'Force producers to reconnect every minute',
      'Persist every metric synchronously in request path',
      'Set one fixed consumer count forever',
    ],
    correctIndex: 1,
    correctExplanation: 'Lag-aware scaling and admission controls handle burst dynamics better than static throughput assumptions.',
  },
  {
    id: 'hard-distributed-latency-10-q6',
    difficulty: 'hard',
    prompt: 'Tail latency worsens after introducing cross-service auth checks. Best hardening approach?',
    options: [
      'Inline token introspection on every call without caching',
      'Cache verifiable auth metadata with bounded TTL and fail-safe policy for critical paths',
      'Remove auth checks from internal APIs',
      'Move auth checks after response write',
      'Retry auth calls indefinitely',
      'Replace auth service with synchronous DB lookups per request',
    ],
    correctIndex: 1,
    correctExplanation: 'Bounded metadata caching with explicit fail policy reduces auth hop latency while maintaining security posture.',
  },
]

export default data
