import { buildLeetcodePatternQuestion } from '../patternOptions'

function richPrompt(params: {
  title: string
  fullProblem: string
  io: string
  constraints: string
  objective: string
}): string {
  return (
    `${params.title}\n\n` +
    `Full Problem Statement: ${params.fullProblem}\n` +
    `Input/Output Requirements: ${params.io}\n` +
    `Constraints and Edge Cases: ${params.constraints}\n\n` +
    `Pattern Selection Question: ${params.objective}`
  )
}

const data = [
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc169-majority-element-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 169 - Majority Element',
      fullProblem: 'Given an array of size n, return the majority element that appears more than floor(n/2) times.',
      io: 'Input: integer array nums. Output: the majority value.',
      constraints: 'Need linear time and constant extra memory if possible.',
      objective: 'Which voting pattern cancels out different values to isolate the majority candidate?',
    }),
    correctPattern: 'Boyer-Moore Voting Algorithm',
    correctExplanation: 'Track a candidate and counter; matching values increment and different values decrement, leaving majority candidate.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc228-summary-ranges-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 228 - Summary Ranges',
      fullProblem: 'Given a sorted unique integer array, return shortest sorted list of ranges that exactly cover all numbers.',
      io: 'Input: sorted unique nums. Output: list of range strings.',
      constraints: 'Need detect maximal consecutive runs in one pass.',
      objective: 'Which one-direction scan pattern tracks run starts and ends as pointers move forward?',
    }),
    correctPattern: 'Two Pointers (Same Direction / Fast and Slow)',
    correctExplanation: 'Advance a fast pointer through consecutive values while slow marks run start, then emit each completed range.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc389-find-the-difference-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 389 - Find the Difference',
      fullProblem: 'String t is generated by shuffling s and adding one extra letter. Return the added letter.',
      io: 'Input: strings s and t. Output: single extra character.',
      constraints: 'Should avoid heavy auxiliary structures for simple cancellation.',
      objective: 'Which bitwise cancellation technique reveals the unmatched character directly?',
    }),
    correctPattern: 'Bit Manipulation Tricks',
    correctExplanation: 'XOR all characters from s and t; paired characters cancel, leaving only the extra character.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc202-happy-number-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 202 - Happy Number',
      fullProblem: 'Repeatedly replace number by sum of squares of digits. Return true if process reaches 1, false if it loops forever.',
      io: 'Input: integer n. Output: boolean happy-or-cycle result.',
      constraints: 'Need cycle detection over generated sequence without unbounded memory.',
      objective: 'Which fast/slow pointer cycle-detection pattern works on this number transition function?',
    }),
    correctPattern: "Fast and Slow Pointers (Floyd's Cycle Detection)",
    correctExplanation: 'Treat transformation as linked sequence and use tortoise-hare pointers to detect non-1 cycles.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc141-linked-list-cycle-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 141 - Linked List Cycle',
      fullProblem: 'Given head of linked list, determine whether the list contains a cycle.',
      io: 'Input: linked list head. Output: true if cycle exists, else false.',
      constraints: 'Need O(1) extra space solution preferred.',
      objective: 'Which classic pointer-speed pattern detects cycle existence without extra storage?',
    }),
    correctPattern: "Fast and Slow Pointers (Floyd's Cycle Detection)",
    correctExplanation: 'Slow moves one step and fast moves two; if they meet, a cycle exists.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc206-reverse-linked-list-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 206 - Reverse Linked List',
      fullProblem: 'Reverse a singly linked list and return the new head.',
      io: 'Input: linked list head. Output: head of reversed list.',
      constraints: 'Should be done iteratively in O(n) time and O(1) extra space.',
      objective: 'Which pointer rewiring pattern is the standard in-place approach?',
    }),
    correctPattern: 'In-place Linked List Reversal',
    correctExplanation: 'Iteratively re-point next references using prev/curr/next pointers until list is reversed.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc21-merge-two-sorted-lists-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 21 - Merge Two Sorted Lists',
      fullProblem: 'Merge two sorted singly linked lists into one sorted list by splicing nodes.',
      io: 'Input: heads of two sorted lists. Output: head of merged sorted list.',
      constraints: 'Need clean pointer handling, especially at list head creation.',
      objective: 'Which linked-list construction pattern simplifies head/tail edge cases during merge?',
    }),
    correctPattern: 'Dummy Head Technique',
    correctExplanation: 'A dummy starter node avoids special-case handling for first insertion and simplifies tail appends.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc876-middle-of-the-linked-list-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 876 - Middle of the Linked List',
      fullProblem: 'Return the middle node of linked list; if two middle nodes, return the second one.',
      io: 'Input: linked list head. Output: middle node reference.',
      constraints: 'Need one-pass solution without computing full length first.',
      objective: 'Which pointer strategy locates midpoint by using different traversal speeds?',
    }),
    correctPattern: 'Fast and Slow Pointers (Midpoint)',
    correctExplanation: 'Fast moves two nodes while slow moves one; when fast ends, slow is at the middle.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc977-squares-of-a-sorted-array-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 977 - Squares of a Sorted Array',
      fullProblem: 'Given sorted integer array (possibly negative), return array of squared values sorted non-decreasingly.',
      io: 'Input: sorted nums. Output: sorted squares array.',
      constraints: 'Largest square can come from either extreme because of absolute values.',
      objective: 'Which bidirectional pointer pattern fills output from the end by comparing extremes?',
    }),
    correctPattern: 'Two Pointers (Opposite Direction)',
    correctExplanation: 'Compare absolute values at left/right ends and place larger square at current output back index.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc530-minimum-absolute-difference-in-bst-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 530 - Minimum Absolute Difference in BST',
      fullProblem: 'Given BST root, return minimum absolute difference between values of any two nodes.',
      io: 'Input: BST root. Output: minimum absolute difference integer.',
      constraints: 'Need exploit BST sorted-order property without flattening with heavy overhead.',
      objective: 'Which traversal pattern yields node values in sorted order for adjacent-difference checks?',
    }),
    correctPattern: 'Tree DFS (In-order)',
    correctExplanation: 'In-order traversal of BST is sorted, so minimum difference occurs between neighboring visited values.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc997-find-the-town-judge-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 997 - Find the Town Judge',
      fullProblem: 'In town of n people labeled 1..n, judge trusts nobody and everybody else trusts judge. Given trust pairs, return judge label or -1.',
      io: 'Input: n and trust edges. Output: judge id or -1.',
      constraints: 'Need accumulate trust in/out counts for all nodes efficiently.',
      objective: 'Which array-marking/counting pattern computes candidate by indegree-outdegree signatures?',
    }),
    correctPattern: 'In-place Array Hashing / Marking',
    correctExplanation: 'Track indegree and outdegree per person; judge must have indegree n-1 and outdegree 0.',
  }),
  buildLeetcodePatternQuestion({
    id: 'leetcode-pattern-type-easy-lc746-min-cost-climbing-stairs-additional-20',
    difficulty: 'easy',
    prompt: richPrompt({
      title: 'LeetCode 746 - Min Cost Climbing Stairs',
      fullProblem: 'You can climb 1 or 2 steps and pay cost of stepped-on stair. Return minimum cost to reach top beyond last index.',
      io: 'Input: cost array. Output: minimum total climbing cost.',
      constraints: 'Each state depends on the previous two decisions.',
      objective: 'Which one-dimensional DP pattern with two-step recurrence best models this problem?',
    }),
    correctPattern: '1D DP (Fibonacci / Climbing Stairs Pattern)',
    correctExplanation: 'Use recurrence dp[i] = cost[i] + min(dp[i-1], dp[i-2]) and derive minimum cost to reach top.',
  }),
]

export default data
